export const ERROR_CATALOG = {
  BAD_REQUEST: { httpStatus: 400, category: 'generic', description: 'A requisicao nao passou nas validacoes basicas de contrato.' },
  UNAUTHORIZED: { httpStatus: 401, category: 'generic', description: 'A requisicao exige autenticacao valida.' },
  FORBIDDEN: { httpStatus: 403, category: 'generic', description: 'A requisicao foi autenticada, mas nao possui permissao suficiente.' },
  NOT_FOUND: { httpStatus: 404, category: 'generic', description: 'O recurso solicitado nao foi encontrado.' },
  CONFLICT: { httpStatus: 409, category: 'generic', description: 'A operacao conflitou com o estado atual dos dados.' },
  PAYLOAD_TOO_LARGE: { httpStatus: 413, category: 'generic', description: 'O corpo da requisicao excedeu o limite configurado.' },
  RATE_LIMITED: { httpStatus: 429, category: 'generic', description: 'A taxa de requisicoes excedeu o limite permitido.' },
  INTERNAL_SERVER_ERROR: { httpStatus: 500, category: 'generic', description: 'Erro interno inesperado.' },
  VALIDATION_ERROR: { httpStatus: 400, category: 'generic', description: 'Os dados informados nao passaram na validacao.' },

  HOST_HEADER_INVALID: { httpStatus: 400, category: 'infra', description: 'O cabecalho Host enviado pelo cliente e invalido.' },
  RATE_LIMIT_GLOBAL: { httpStatus: 429, category: 'rate-limit', description: 'Limite global de requisicoes excedido.' },
  RATE_LIMIT_LOGIN: { httpStatus: 429, category: 'rate-limit', description: 'Limite de tentativas de login excedido.' },
  RATE_LIMIT_REGISTER: { httpStatus: 429, category: 'rate-limit', description: 'Limite de tentativas de cadastro excedido.' },
  RATE_LIMIT_COMMENT_RELEVANCE_VOTE: { httpStatus: 429, category: 'rate-limit', description: 'Limite de votos de relevancia excedido.' },

  ADMIN_ACCESS_REQUIRED: { httpStatus: 403, category: 'auth', description: 'A operacao exige perfil de administrador.' },
  ADMIN_USER_ID_INVALID: { httpStatus: 400, category: 'admin', description: 'O identificador do usuario administrado e invalido.' },
  ADMIN_USER_NOT_FOUND: { httpStatus: 404, category: 'admin', description: 'O usuario administrado nao foi encontrado.' },
  ADMIN_POST_ID_INVALID: { httpStatus: 400, category: 'admin', description: 'O identificador do post administrado e invalido.' },
  ADMIN_POST_NOT_FOUND: { httpStatus: 404, category: 'admin', description: 'O post administrado nao foi encontrado.' },
  ADMIN_COMMENT_ID_INVALID: { httpStatus: 400, category: 'admin', description: 'O identificador do comentario administrado e invalido.' },
  ADMIN_COMMENT_NOT_FOUND: { httpStatus: 404, category: 'admin', description: 'O comentario administrado nao foi encontrado.' },

  AUTH_TOKEN_MISSING: { httpStatus: 401, category: 'auth', description: 'Nenhuma credencial de autenticacao foi enviada.' },
  AUTH_SESSION_INVALID: { httpStatus: 401, category: 'auth', description: 'A sessao enviada nao pode ser validada.' },
  AUTH_TOKEN_INVALID: { httpStatus: 401, category: 'auth', description: 'O token enviado e invalido ou expirou.' },
  AUTH_REGISTER_INVALID_PAYLOAD: { httpStatus: 400, category: 'auth', description: 'Payload invalido para cadastro.' },
  AUTH_GOOGLE_INVALID_PAYLOAD: { httpStatus: 400, category: 'auth', description: 'Payload invalido para autenticacao com Google.' },
  AUTH_LINK_GOOGLE_REQUIRES_SESSION: { httpStatus: 401, category: 'auth', description: 'Vinculo de conta Google exige sessao autenticada.' },
  AUTH_LINK_GOOGLE_INVALID_PAYLOAD: { httpStatus: 400, category: 'auth', description: 'Payload invalido para vinculo de conta Google.' },
  AUTH_LOGIN_INVALID_PAYLOAD: { httpStatus: 400, category: 'auth', description: 'Payload invalido para login.' },
  AUTH_REFRESH_TOKEN_INVALID: { httpStatus: 401, category: 'auth', description: 'Refresh token invalido ou revogado.' },
  AUTH_REFRESH_USER_NOT_FOUND: { httpStatus: 401, category: 'auth', description: 'Usuario do refresh token nao encontrado.' },

  GOOGLE_EMAIL_NOT_VERIFIED: { httpStatus: 400, category: 'auth', description: 'A conta Google ainda nao possui e-mail verificado.' },
  GOOGLE_LINK_CONFLICT: { httpStatus: 403, category: 'auth', description: 'A conta Google nao corresponde ao vinculo existente.' },
  GOOGLE_LINK_EMAIL_MISMATCH: { httpStatus: 409, category: 'auth', description: 'O e-mail da conta Google nao corresponde ao esperado para o vinculo.' },
  GOOGLE_PROVIDER_ALREADY_LINKED: { httpStatus: 409, category: 'auth', description: 'A conta Google ja esta vinculada a outro perfil.' },

  USER_ME_AUTH_REQUIRED: { httpStatus: 401, category: 'user', description: 'Leitura do proprio perfil exige autenticacao.' },
  USER_ME_NOT_FOUND: { httpStatus: 404, category: 'user', description: 'O usuario autenticado nao foi encontrado.' },
  USER_UPDATE_AUTH_REQUIRED: { httpStatus: 401, category: 'user', description: 'Atualizacao de perfil exige autenticacao.' },
  USER_UPDATE_INVALID_PAYLOAD: { httpStatus: 400, category: 'user', description: 'Payload invalido para atualizacao de perfil.' },
  USER_UPDATE_INVALID_DATA: { httpStatus: 400, category: 'user', description: 'Os dados de perfil enviados sao invalidos.' },
  USER_DELETE_AUTH_REQUIRED: { httpStatus: 401, category: 'user', description: 'Exclusao de conta exige autenticacao.' },
  USER_ID_INVALID: { httpStatus: 400, category: 'user', description: 'O identificador do usuario e invalido.' },
  USER_NOT_FOUND: { httpStatus: 404, category: 'user', description: 'O usuario solicitado nao foi encontrado.' },

  BOOK_ID_INVALID: { httpStatus: 400, category: 'book', description: 'O identificador do livro e invalido.' },
  BOOK_NOT_FOUND: { httpStatus: 404, category: 'book', description: 'O livro solicitado nao foi encontrado.' },
  BOOK_CREATE_INVALID_PAYLOAD: { httpStatus: 400, category: 'book', description: 'Payload invalido para criacao de livro.' },
  BOOK_ISBN_CONFLICT: { httpStatus: 409, category: 'book', description: 'Ja existe um livro com o ISBN informado.' },
  BOOK_CREATE_INVALID_DATA: { httpStatus: 400, category: 'book', description: 'Os dados enviados para criacao do livro sao invalidos.' },
  BOOK_UPDATE_INVALID_PAYLOAD: { httpStatus: 400, category: 'book', description: 'Payload invalido para atualizacao de livro.' },
  BOOK_UPDATE_INVALID_DATA: { httpStatus: 400, category: 'book', description: 'Os dados enviados para atualizacao do livro sao invalidos.' },

  COMMENT_POST_ID_INVALID: { httpStatus: 400, category: 'comment', description: 'O identificador do post vinculado ao comentario e invalido.' },
  COMMENT_POST_NOT_FOUND: { httpStatus: 404, category: 'comment', description: 'O post vinculado ao comentario nao foi encontrado.' },
  COMMENT_USER_ID_INVALID: { httpStatus: 400, category: 'comment', description: 'O identificador do usuario do comentario e invalido.' },
  COMMENT_ID_INVALID: { httpStatus: 400, category: 'comment', description: 'O identificador do comentario e invalido.' },
  COMMENT_NOT_FOUND: { httpStatus: 404, category: 'comment', description: 'O comentario solicitado nao foi encontrado.' },
  COMMENT_NOT_VISIBLE: { httpStatus: 404, category: 'comment', description: 'O comentario existe, mas nao esta visivel para o usuario atual.' },
  COMMENT_CREATE_AUTH_REQUIRED: { httpStatus: 401, category: 'comment', description: 'Criacao de comentario exige autenticacao.' },
  COMMENT_CREATE_INVALID_PAYLOAD: { httpStatus: 400, category: 'comment', description: 'Payload invalido para criacao de comentario.' },
  COMMENT_UPDATE_AUTH_REQUIRED: { httpStatus: 401, category: 'comment', description: 'Atualizacao de comentario exige autenticacao.' },
  COMMENT_UPDATE_INVALID_PAYLOAD: { httpStatus: 400, category: 'comment', description: 'Payload invalido para atualizacao de comentario.' },
  COMMENT_DELETE_AUTH_REQUIRED: { httpStatus: 401, category: 'comment', description: 'Exclusao de comentario exige autenticacao.' },
  COMMENT_RELEVANCE_VOTE_AUTH_REQUIRED: { httpStatus: 401, category: 'comment', description: 'Voto de relevancia exige autenticacao.' },
  COMMENT_RELEVANCE_VOTE_INVALID_PAYLOAD: { httpStatus: 400, category: 'comment', description: 'Payload invalido para voto de relevancia.' },

  NOTEBOOK_LIST_AUTH_REQUIRED: { httpStatus: 401, category: 'notebook', description: 'Listagem de registros de leitura exige autenticacao.' },
  NOTEBOOK_CREATE_AUTH_REQUIRED: { httpStatus: 401, category: 'notebook', description: 'Criacao de registro de leitura exige autenticacao.' },
  NOTEBOOK_CREATE_INVALID_PAYLOAD: { httpStatus: 400, category: 'notebook', description: 'Payload invalido para criacao de registro de leitura.' },
  NOTEBOOK_UPDATE_AUTH_REQUIRED: { httpStatus: 401, category: 'notebook', description: 'Atualizacao de registro de leitura exige autenticacao.' },
  NOTEBOOK_ID_INVALID: { httpStatus: 400, category: 'notebook', description: 'O identificador do registro de leitura e invalido.' },
  NOTEBOOK_UPDATE_INVALID_PAYLOAD: { httpStatus: 400, category: 'notebook', description: 'Payload invalido para atualizacao de registro de leitura.' },
  NOTEBOOK_DELETE_AUTH_REQUIRED: { httpStatus: 401, category: 'notebook', description: 'Exclusao de registro de leitura exige autenticacao.' },

  POST_BOOK_ID_INVALID: { httpStatus: 400, category: 'post', description: 'O identificador do livro vinculado ao post e invalido.' },
  POST_USER_ID_INVALID: { httpStatus: 400, category: 'post', description: 'O identificador do usuario do post e invalido.' },
  POST_DRAFT_AUTH_REQUIRED: { httpStatus: 401, category: 'post', description: 'Leitura de rascunho exige autenticacao.' },
  POST_DRAFT_QUERY_INVALID: { httpStatus: 400, category: 'post', description: 'Query invalida para leitura de rascunho.' },
  POST_ID_INVALID: { httpStatus: 400, category: 'post', description: 'O identificador do post e invalido.' },
  POST_NOT_FOUND: { httpStatus: 404, category: 'post', description: 'O post solicitado nao foi encontrado.' },
  POST_NOT_VISIBLE: { httpStatus: 404, category: 'post', description: 'O post existe, mas nao esta visivel para o usuario atual.' },
  POST_DRAFT_SAVE_AUTH_REQUIRED: { httpStatus: 401, category: 'post', description: 'Salvar rascunho exige autenticacao.' },
  POST_DRAFT_SAVE_INVALID_PAYLOAD: { httpStatus: 400, category: 'post', description: 'Payload invalido para salvar rascunho.' },
  POST_DRAFT_DELETE_AUTH_REQUIRED: { httpStatus: 401, category: 'post', description: 'Excluir rascunho exige autenticacao.' },
  POST_DRAFT_DELETE_QUERY_INVALID: { httpStatus: 400, category: 'post', description: 'Query invalida para exclusao de rascunho.' },
  POST_CREATE_AUTH_REQUIRED: { httpStatus: 401, category: 'post', description: 'Criacao de post exige autenticacao.' },
  POST_CREATE_INVALID_PAYLOAD: { httpStatus: 400, category: 'post', description: 'Payload invalido para criacao de post.' },
  POST_UPDATE_AUTH_REQUIRED: { httpStatus: 401, category: 'post', description: 'Atualizacao de post exige autenticacao.' },
  POST_UPDATE_INVALID_PAYLOAD: { httpStatus: 400, category: 'post', description: 'Payload invalido para atualizacao de post.' },
  POST_DELETE_AUTH_REQUIRED: { httpStatus: 401, category: 'post', description: 'Exclusao de post exige autenticacao.' },

  SERIES_BOOK_ID_INVALID: { httpStatus: 400, category: 'series', description: 'O identificador do livro usado para lookup de serie e invalido.' },
  SERIES_NOT_FOUND: { httpStatus: 404, category: 'series', description: 'A serie solicitada nao foi encontrada.' },

  UPLOAD_PROFILE_AUTH_REQUIRED: { httpStatus: 401, category: 'upload', description: 'Upload de imagem de perfil exige autenticacao.' },
  UPLOAD_PROFILE_INVALID_PAYLOAD: { httpStatus: 400, category: 'upload', description: 'Payload invalido para assinatura de upload de perfil.' },
  UPLOAD_BOOK_COVER_AUTH_REQUIRED: { httpStatus: 401, category: 'upload', description: 'Upload de capa exige autenticacao.' },
  UPLOAD_BOOK_COVER_INVALID_PAYLOAD: { httpStatus: 400, category: 'upload', description: 'Payload invalido para assinatura de upload de capa.' },

  SEARCH_QUERY_REQUIRED: { httpStatus: 400, category: 'search', description: 'A busca externa exige o parametro q.' },
  SEARCH_IMPORT_INVALID_PAYLOAD: { httpStatus: 400, category: 'search', description: 'Payload invalido para importacao de livro externo.' },
  SEARCH_IMPORT_ISBN_CONFLICT: { httpStatus: 409, category: 'search', description: 'A importacao falhou porque o ISBN ja existe.' },
  SEARCH_IMPORT_INVALID_DATA: { httpStatus: 400, category: 'search', description: 'Os dados do livro externo sao invalidos para importacao.' },
} as const;

export type ApiErrorCode = keyof typeof ERROR_CATALOG;

export function isApiErrorCode(code: string): code is ApiErrorCode {
  return code in ERROR_CATALOG;
}